#!/usr/bin/env bash
cd ~
guix shell --network --container --emulate-fhs -m ~/.manifests/rust_dev.scm -m ~/.manifests/emacs.scm --preserve='^DISPLAY$' --share=$HOME/Projects/Rust=$HOME --expose=$HOME/.emacs.d/init.el=$HOME/.emacs.d/init.el
