#!/usr/bin/env bash
guix pull

# garbage collection
sudo guix gc -d 2m -F 50G # delete generations more than two months old, leave at least 50G of space left

# update system
sudo -E guix system reconfigure ~/.config/guix/system.scm

# update home
guix home reconfigure ~/.dotfiles/.config/guix/home-configuration.scm

# update rust-dev
guix package -m ~/.dotfiles/.manifests/emacs.scm -m ~/.dotfiles/.manifests/rust_dev.scm -p ~/.guix-extra-profiles/rust-dev
